### ISSUE TITLE
Doenst work on 1.21.10

### ISSUE THREAD

**Issue by tooobiiii** [r0yzer/perspektive#30]
^^

**Comment by QuanOnTheCob** [comment]
Bumping this. And since there's barely any info on the original post, here's my crash log

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2025-11-29 13:08:12
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'perspektive' at 'de.royzer.perspektive.MainKt::initClient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:483)
	at knot//net.minecraft.client.main.Main.main(Main.java:234)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_304.<init>(java.lang.String, net.minecraft.class_3675$class_307, int, java.lang.String)'
	at knot//de.royzer.perspektive.Perspektive.<clinit>(Perspektive.kt:26)
	at knot//de.royzer.perspektive.MainKt.initClient(Main.kt:6)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy36.onInitializeClient(Unknown Source)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
	... 6 more
```

Full log is probably too long so I placed it [here](https://pastebin.com/4CKfM96u) instead.

**Comment by r0yzer** [comment]
should work now, please reopen if still crashes
